spring:
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://$***REMOVED***app.auth-server.host***REMOVED***:$***REMOVED***app.auth-server.port***REMOVED***/.well-known/jwks.json
  # As Spring Cloud Ribbon is in maintenance mode.
  # It is recommended switching to BlockingLoadBalancerClient instead.
  cloud:
    # Route definitions of the system
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: store-products
          # lb:// is used to direct Spring Cloud Gateway to use the client-side load balancer
          # to look up the destination in the discovery service.
          uri: lb://store
          predicates:
            - Path=/store/**

        - id: oauth-server
          uri: lb://auth-server
          predicates:
            - Path=/oauth/**

        - id: eureka-api
          uri: http://$***REMOVED***app.eureka.host***REMOVED***:$***REMOVED***app.eureka.port***REMOVED***
          predicates:
            - Path=/eureka/api/***REMOVED***segment***REMOVED***
          filters:
            - SetPath=/eureka/***REMOVED***segment***REMOVED***

        - id: eureka-web-start
          uri: http://$***REMOVED***app.eureka.host***REMOVED***:$***REMOVED***app.eureka.port***REMOVED***
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://$***REMOVED***app.eureka.host***REMOVED***:$***REMOVED***app.eureka.port***REMOVED***
          predicates:
            - Path=/eureka/**

        - id: config-server
          uri: http://$***REMOVED***app.config-server.host***REMOVED***:$***REMOVED***app.config-server.port***REMOVED***
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /$\***REMOVED***segment***REMOVED***

        # Testing URLs
        - id: host_route_200
          uri: http://httpstat.us
          predicates:
            - Host=i.feel.lucky:8080
            - Path=/headerrouting/**
          filters:
            - SetPath=/200

        - id: host_route_418
          uri: http://httpstat.us
          predicates:
            - Host=im.a.teapot:8080
            - Path=/headerrouting/**
          filters:
            - SetPath=/418

        - id: host_route_501
          uri: http://httpstat.us
          predicates:
            - Path=/headerrouting/**
          filters:
            - SetPath=/501

server:
  port: 8443 # SSL Port
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/test.p12
    key-store-password: testtest
    key-alias: localhost

logging.level:
  org.springframework.cloud.gateway: TRACE
  org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
  org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE

***REMOVED***
spring:
  profiles: external-OAuth-Provider
  security.oauth2.resourceserver:
    jwt.jwk-set-uri: https://dev-taman.eu.auth0.com/.well-known/jwks.json
