spring:
  application.name: product
  data:
    mongodb:
      host: $***REMOVED***app.database.host***REMOVED***
      port: 27017
      database: product-db
      auto-index-creation: true

  rabbitmq:
    host: $***REMOVED***app.messaging.rabbitmq.host***REMOVED***
    port: 5672
    username: guest
    password: guest

  cloud:
    # As Spring Cloud Ribbon is in maintenance mode.
    # It is recommended switching to BlockingLoadBalancerClient instead.
    loadbalancer.ribbon.enabled: false

    # Event-driven messages Stream config
    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        input:
          destination: products
          group: productsGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      rabbit:
        bindings:
          input.consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        bindings:
          input.consumer.enableDlq: true
        binder:
          brokers: $***REMOVED***app.messaging.kafka.broker***REMOVED***
          defaultBrokerPort: 9092

server:
  port: 9081

logging.level:
    web: DEBUG
    root: INFO
    com.siriusxi.ms.store: DEBUG
    org:
      springframework.data.mongodb.core.MongoTemplate: DEBUG
      mongodb: debug

management:
  info.git:
      mode: full
      enabled: true
  endpoints.web.exposure.include: "*"
  endpoint:
    shutdown.enabled: true
    health.show-details: always

app:
  eureka-server: localhost
  database:
    host: localhost
  messaging:
    rabbitmq.host: 127.0.0.1
    kafka.broker: 127.0.0.1

# Service discovery configs
eureka:
  client:
    healthcheck.enabled: true
    service-url.defaultZone: http://$***REMOVED***app.eureka-server***REMOVED***:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

# This is a docker specific profile properties
# Also profiles could be separated in its owen file
# with file name format of "application-docker.yaml"
***REMOVED***
spring:
  profiles: docker
  jmx.enabled: false

server.port: 8080

app:
  eureka-server: eureka
  database:
    host: mongodb
  messaging:
    rabbitmq.host: rabbitmq
    kafka.broker: kafka
