spring:
  application.name: auth-server

  # As Spring Cloud Ribbon is in maintenance mode.
  # It is recommended switching to BlockingLoadBalancerClient instead.
  cloud:
    loadbalancer.ribbon.enabled: false

server:
  port: 9999
  error:
    include-message: always
    include-binding-errors: always

# Define Security
app:
  eureka:
    host: localhost
    user: mt
    pass: p

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
  client:
    healthcheck.enabled: true
    service-Url:
      defaultZone: http://$***REMOVED***app.eureka.user***REMOVED***:$***REMOVED***app.eureka.pass***REMOVED***@$***REMOVED***app.eureka.host***REMOVED***:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5

ribbon:
  server-list-refresh-interval: 5000
  NF-load-balancer-ping-interval: 5

management:
  info.git:
    enabled: true
    mode: full
  endpoint:
    health.show-details: "ALWAYS"
  endpoints:
    web.exposure.include: "*"

# security.oauth2.authorizationserver.jwt.enabled: false


***REMOVED***
spring.profiles: docker

app:
  eureka:
    host: eureka